# Generated by Django 5.1.3 on 2024-12-04 22:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"ordering": ["-name"]},
        ),
        migrations.AlterModelOptions(
            name="company",
            options={"ordering": ["-name"]},
        ),
    ]
