# Generated by Django 5.1.3 on 2024-12-05 01:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_alter_author_options_alter_company_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="company",
            options={"ordering": ["name"]},
        ),
    ]
