# Generated by Django 5.1.3 on 2024-12-04 03:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="author_name",
            new_name="author",
        ),
        migrations.AlterUniqueTogether(
            name="post",
            unique_together={("year", "month", "company", "author")},
        ),
    ]
