# Generated by Django 5.1.3 on 2024-12-05 01:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_rename_author_name_post_author_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-year", "-month", "company__name"]},
        ),
    ]
